# Locations of important files and folders
LogFile:          "data/log backend.txt"        # Log file for the backend. It contains informational and error messages.
BlockchainMain:   "data/blockchain main/"       # Blockchain main stores the end-users blockchain data. It contains meta data of shared files, profile data, and social interactions.
BlockchainGlobal: "data/blockchain global/"     # Blockchain global caches blockchain data from global users. Empty to disable.
WarehouseMain:    "data/warehouse main/"        # Warehouse main stores the actual data of files shared by the end-user.
SearchIndex:      "data/search index/"          # Local search index of blockchain records. Empty to disable.
GeoIPDatabase:    "data/GeoLite2-City.mmdb"     # GeoLite2 City database to provide GeoIP information.
DataFolder:       "data/"                       # Data folder.

# Listen defines all IP:Port combinations to listen on. If empty, it will listen on all IPs automatically on available ports.
# IPv6 must be in the form "[IPv6]:Port". This setting is only recommended to be set on servers.
Listen: []

# Count of workers to process incoming raw packets. Default 2.
ListenWorkers: 0

# Count of workers to process incoming lite packets. Default 2.
ListenWorkersLite: 0

# AutoUpdateSeedList enables auto update of the seed list.
AutoUpdateSeedList: true

# Initial peer seed list. If AutoUpdateSeedList is enabled then any changes will be overwritten on update.
SeedListVersion: 1
SeedList:
  - PublicKey: 02c490e4252bc7608fd55ddd9d7ca4a488ad152f3da6a6c2e9061f4c7e59f5b7f8 # 1.peernet.network
    Address: ["185.254.123.112:112","[2a0c:1880::112]:112"]
  - PublicKey: 02b270f6fdac85e76df0d2f7374f33a620ede82542ff7cd62d6934b4c069921322 # 2.peernet.network
    Address: ["167.99.45.141:112","[2a03:b0c0:2:d0::af0:e001]:112"]
  - PublicKey: 026836d40a77779b7df5f1a08ca1ef8a83e15edcf0e4d8dc6ed5fc351cb60bd07c # 3.peernet.network
    Address: ["[2a0b:6580::238:112]:112"]
  - PublicKey: 0382728d11096efb211de8a9b7bb90f8e248be5572d4f5449f58a2af881b22dbe9 # 4.peernet.network
    Address: ["178.18.241.68:112","[2a02:c206:2056:9660::1]:112"]
  - PublicKey: 03174f370cb6d6f361d0511565b6b456a82c3d16b53d6b63b227d76a4f0f2abd2c # 5.peernet.network
    Address: ["194.233.66.99:112","[2407:3640:2057:5241::1]:112"]

# Connection settings
EnableUPnP:     true    # Enables support for UPnP.
LocalFirewall:  false   # Indicates that a local firewall may drop unsolicited incoming packets.

# PortForward specifies an external port that was manually forwarded by the user. All listening IPs must have that same port number forwarded!
# If this setting is invalid, it will prohibit other peers from connecting. If set, it automatically disables UPnP.
PortForward: 0          # Default not set.

# Global blockchain cache limits
CacheMaxBlockSize:    4096  # Max block size to accept in bytes.
CacheMaxBlockCount:   256   # Max block count to cache per peer.
LimitTotalRecords:    0     # Record count limit. 0 = unlimited. Max Records * Max Block Size = Size Limit.
